#!/bin/bash

# Update package list and install nginx
sudo apt-get update -y
sudo apt-get install nginx -y

# Ensure Nginx is running
sudo service nginx start

# Create a custom HTML page with "Hello World!" in the root directory
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

# Restart Nginx (without using systemctl)
sudo service nginx reload
