#!/bin/bash

# Update package list
sudo apt-get update -y

# Install nginx
sudo apt-get install nginx -y

# Start Nginx
sudo service nginx start

# Create a custom HTML page with "Hello World!" in the root directory
echo "Hello World!" | sudo tee /var/www/html/index.html

# Reload Nginx to apply changes
sudo service nginx reload
