#!/usr/bin/env bash
# This script tells a story based on the content of the file /etc/passwd

while IFS=":" read -r username _ userid groupid _ home shell
do
    passcode=$(grep -w "^$username" /etc/shadow | cut -d ":" -f 2)
    userinfo=$(grep -w "^$username" /etc/passwd)
    echo "The user $username is part of the $groupid gang, lives in $home and rides $shell. $userid's place is protected by the passcode $passcode, more info about the user here: $userinfo"
done < /etc/passwd

