#!/bin/bash

# Script to generate an RSA key pair with specific requirements

# Define variables
KEY_NAME="school"
KEY_BITS=4096
PASSPHRASE="betty"

# Generate the RSA key pair
ssh-keygen -t rsa -b $KEY_BITS -f $KEY_NAME -N $PASSPHRASE
